- name: Clone django project repository
  git:
    repo: "{{repository}}"
    dest: "/home/{{server_user}}/{{project_name}}"
    version: "{{repository_branch}}"
  become_user: "{{server_user}}"

- name: Install production.py
  template:
    src: production.py
    dest: "/home/{{server_user}}/{{project_name}}/{{project_settings_path}}/production.py"
  become_user: "{{server_user}}"

- name: Install env.vars
  template:
    src: env.sh
    dest: "/home/{{server_user}}/{{project_name}}/env.sh"
  become_user: "{{server_user}}"

- name: Create virtualenv and run pip install -r requirement.txt
  pip:
    requirements: "/home/{{server_user}}/{{project_name}}/requirements.txt"
    virtualenv: "/home/{{server_user}}/{{project_name}}/venv"
    virtualenv_python: python3
  become_user: "{{server_user}}"

- name: Run migrate
  django_manage:
    command: migrate
    app_path: "/home/{{server_user}}/{{project_name}}"
    settings: "{{project_main_settings_file}}"
    virtualenv: "/home/{{server_user}}/{{project_name}}/venv"
  become_user: "{{server_user}}"
  environment:
    SECRET_KEY: "{{secret_key}}"
    DB_NAME: "{{db_name}}"
    DB_USER: "{{db_user}}"
    DB_PASS: "{{db_pass}}"
    AWS_STORAGE_BUCKET_NAME: "{{aws_storage_bucket_name}}"
    AWS_S3_REGION_NAME: "{{aws_s3_region_name}}"
    AWS_ACCESS_KEY_ID: "{{aws_access_key_id}}"
    AWS_S3_CUSTOM_DOMAIN: "{{aws_s3_custom_domain}}"
    AWS_SECRET_ACCESS_KEY: "{{aws_secret_access_key}}"

- name: Run collectstatic
  django_manage:
    command: collectstatic
    app_path: "/home/{{server_user}}/{{project_name}}"
    settings: "{{project_main_settings_file}}"
    virtualenv: "/home/{{server_user}}/{{project_name}}/venv"
  become_user: "{{server_user}}"
  environment:
    SECRET_KEY: "{{secret_key}}"
    DB_NAME: "{{db_name}}"
    DB_USER: "{{db_user}}"
    DB_PASS: "{{db_pass}}"
    AWS_STORAGE_BUCKET_NAME: "{{aws_storage_bucket_name}}"
    AWS_S3_REGION_NAME: "{{aws_s3_region_name}}"
    AWS_ACCESS_KEY_ID: "{{aws_access_key_id}}"
    AWS_S3_CUSTOM_DOMAIN: "{{aws_s3_custom_domain}}"
    AWS_SECRET_ACCESS_KEY: "{{aws_secret_access_key}}"